[functions]
  directory = "netlify/functions"

[build]
  functions = "netlify/functions"
  command = "npm run build"
  publish = "dist"

[[scheduled.functions]]
  function = "send-reminders"
  cron = "*/5 * * * *"